/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package io.javalin.samples.javalin5.gradleshadow;

import io.javalin.Javalin;

public class App {
    Javalin javalin = Javalin.create()
        .get("/", ctx -> ctx.result("Root"));

    public static void main(String[] args) {
        new App().javalin.start(8080);
    }
}
